drop table if exists USERS;
drop table if exists BOOKINGS;
drop table if exists ITEMS;

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );
CREATE TABLE IF NOT EXISTS ITEMS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key not NULL,
    name VARCHAR(256) NOT NULL,
    description VARCHAR(512) NOT NULL,
    available BOOLEAN NOT NULL,
    owner BIGINT,
    request BIGINT,
    CONSTRAINT fk_user
    FOREIGN KEY(owner)
    REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS BOOKINGS(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item BIGINT,
    booker BIGINT,
    status VARCHAR(64),
    CONSTRAINT fk_item
    FOREIGN KEY(item)
    REFERENCES items(id),
    CONSTRAINT fk_booker
    FOREIGN KEY(booker)
    REFERENCES users(id)
);